### ISSUE TITLE
ロビーで設定した名前をHPゲージと一緒に表示する

### ISSUE THREAD

**Issue by chromee** [denx-jp/SSP#144]
- どのキャラがどのプレイヤーが操作しているか分かるようにするため

**Comment by RauziDssh** [comment]
名前はどのコンポーネントで定義する予定ですか？PlayerModelあたり？

**Comment by chromee** [comment]
どっかのPlayerModelでお願いします！
今はNetworkLobbyHookとかいうLobbyManagerについてるコンポーネントでgameObjectのnameを書き換えるという適当な実装になってるのでそこら辺もmodelのNameを書き換えるように修正お願いします

**Comment by RauziDssh** [comment]
modelのNameを書き換える実装はここのIssueでやる方がいいかと

**Comment by chromee** [comment]
たしかに👍ではそういう方向で

**Comment by RauziDssh** [comment]
いややっぱりこのIssueの優先度が低いので
PlayerModelにNameを乗せる実装は　[こっち](https://github.com/denx-jp/SSP/issues/114)　の方でやります
