### ISSUE TITLE
校舎にコライダーをつける

### ISSUE THREAD

**Issue by chromee** [denx-jp/SSP#23]
- とても大変な作業になりそうですが頑張りましょう…
- プレハブ化されているオブジェクトは一つコライダーをつけてインスペクターからApplyすればプレハブを共有するオブジェクト全てに変更が適用されるので活用しましょう。
- おそらくどこかしらにミスができてしまでしょうが、あまり神経質にならずミスを発見する都度治していくぐらいのつもりでいきましょう。

**Comment by RauziDssh** [comment]
マ？コライダーついてないの？
モデル班にも手伝ってもらうってのはどうですか

**Comment by chromee** [comment]
とりあえず手が空いてる人がやるという感じで…
変に手分けするとコンフリクトしまくってせっかくの努力が無駄になりそうなので分割するにしても段階別に分けるみたいになると思います。

**Comment by RauziDssh** [comment]
なるほど　確かにそうですね

**Comment by tsunosekai** [comment]
校舎のモデルはまだ完成ではないので，ワンフロアだけコライダーを入れるなりして無駄な努力を避けてもらえると助かります

**Comment by tsunosekai** [comment]
コライダーは3DCG班で付けることにします
次提出するモデルではつけておきます
