### ISSUE TITLE
エーテルがランダムにポップするように

### ISSUE THREAD

**Issue by chromee** [denx-jp/SSP#28]
- エーテルオブジェクトがランダムにポップするようにする
- ポップ地点は空のオブジェクトで設定できるようにGameObjectのListで管理する

**Comment by chromee** [comment]
こちら13日までにお願いします

**Comment by Becnick** [comment]
GameObjectのListというのはこれのことですか？
http://qiita.com/okjoesyaony/items/9115ee4303d413a768ff

**Comment by odk224** [comment]
ですです👍

**Comment by odk224** [comment]
`[serializefield] private List<GameObject> 変数名`と書くとインスペクターにリストを表示することができるので、そんな感じでよろしくお願いします
