### ISSUE TITLE
ネットワーク対応準備

### ISSUE THREAD

**Issue by chromee** [denx-jp/SSP#39]
- ネットワーク対応のためのプレイヤーとシーンを作る
- とりあえずTransformの同期だけ
- ネットワークなしの既存の環境でも動くようにする

**Comment by chromee** [comment]
ネットワークとネットワークなしの開発環境を共存させるのって不可能ですね…
ネットワーク用のnetwork-masterみたいなブランチ作ってネットワーク周りはそこで開発するしかなさそうでしょうか？

**Comment by RauziDssh** [comment]
プラットフォーム依存コンパイル機能を使えば一応できることにはできる
https://docs.unity3d.com/jp/540/Manual/PlatformDependentCompilation.html

カスタムDefineシンボルでNetworkとSoloを作れば，1つのコードで2つの環境のコードを共存できる

**Comment by chromee** [comment]
なるほど！
NetworkBehavior継承したコンポーネントをオフラインシーンで使ってるのは特に問題なさそうなのですが、[Command]あたりはエラー吐くのでそこら辺だけカスタムシンボルで分けるようにしてみます👍

**Comment by chromee** [comment]
ネットワーク周りの書こうとして思ったんですけど、やっぱこれNetworkBehaviorのラッパークラス作った方がいい気がしました…

**Comment by chromee** [comment]
このラッパークラスどう思いますか？
https://gist.github.com/chromee/196ae073b1bc3da7c3e48fe0ae4d61e3
