### ISSUE TITLE
アニメーション修正

### ISSUE THREAD

**Issue by chromee** [denx-jp/SSP#53]
いまのスタンダードアセットのやつからRPG Characterのやつに差し替える

**Comment by chromee** [comment]
アセット的な問題でらうじぃさんお願いできますでしょうか

**Comment by RauziDssh** [comment]
攻撃アニメーションはもうRPG Characterのやつになってます
移動アニメーションに関してはStandardAssetのやつがBlendTreeを使ってるんですけど、BlendTreeを使わない方針にしますか？

**Comment by RauziDssh** [comment]
とりあえずBlendTree使ってAnimation置換できそうな部分は置換しておきます

**Comment by RauziDssh** [comment]
あとExternalの部分はmasterにpushしますけどよいですか

**Comment by chromee** [comment]
masterにpushで大丈夫です！
