### ISSUE TITLE
Weaponモデルを作ってインベントリ内の武器のUIを表示する

### ISSUE THREAD

**Issue by chromee** [denx-jp/SSP#73]
- LongRange/ShortRangeWeaponからデータ部分と攻撃処理部分を切り分けるWeaponModelを作る（たぶんLongとShortでModelをわける）
- Imageをインベントリの種類の数だけならべる
- Imageの中に装備名とかをTextでのせる
- 装備中の装備のImageの周りは色枠をつける

**Comment by chromee** [comment]
10/7までにお願いします

**Comment by frontvent** [comment]
「データ部分」はインベントリ内に表示するUIのことでしょうか？

**Comment by chromee** [comment]
modelが持ってる値を全部UIで表示する必要はないですが大体そうですね
武器名・プレイヤーid・チームid・bulletModelあたりはWeaponModelに持たせるようにしてください

**Comment by frontvent** [comment]
プレイヤーid,チームidがよくわかりません
知識不足で申し訳ないです・・・
