### ISSUE TITLE
インベントリ処理のネットワーク対応

### ISSUE THREAD

**Issue by chromee** [denx-jp/SSP#86]
- [ ] インタラクトアクションで武器を拾う処理
- [ ] マウスホイールで武器を切り替える処理
これらのネットワーク対応

**Comment by chromee** [comment]
ここでPlayerのInteractアクション自体をホスト側で行うようにしたので、一応メモ
https://github.com/denx-jp/SSP/pull/103

**Comment by chromee** [comment]
もしかしたらInteractをホスト側で実行するのではなく、クライアント側でInteractしてIInteractableが見つかればそのGameObjectをホストに渡して、ホストでIInteractable.Interact()を実行するようにした方がいいかもしれない。

**Comment by RauziDssh** [comment]
その実装に変えるなら，[ここ](https://github.com/denx-jp/SSP/blob/74c1b23eb3e36e3ddbfea241f524d6e091f0783b/Assets/SSP/Scripts/Player/PlayerInteractor.cs#L49)の部分を差し替えて，CmdInteractはvoid(GameObject)に変更して使う感じでよろしく
[例](https://gist.github.com/RauziDssh/7e202e815d0147e9f4a247bae336f5eb)

確かにInteractするオブジェクトを強調表示したいときとかはchromeeくんが提案してくれた実装の方が良いと思います

**Comment by RauziDssh** [comment]
この前伝えたかもしれないけどメモ
ここの実装，なるべくCmdとかで同期するんじゃなくて，SyncVarで同期すべきかも
（UNETは下部ではUDPで動いてるから，Cmdで状態の同期をしようとするとUDP通信の都合で実行順序がおかしくなるかもしれないので）

**Comment by chromee** [comment]
SyncVarで何を同期させるんですか？

**Comment by RauziDssh** [comment]
武器の持ち替え時にプレイヤーがどの武器を持っているかというのをネットワーク越しで同期する必要があるということです

**Comment by chromee** [comment]
あ～ なるほど　Interactの話かと思ってました。

そのことは自分も実装しようとしてちょっと思いました。
装備中の武器はintで管理できそうなんですけど、所持中の武器ってDictionaryで管理されてるのでちょっと面倒かなって感じです
