### ISSUE TITLE
足音をつける

### ISSUE THREAD

**Issue by chromee** [denx-jp/SSP#94]
- ~~PlayerLocomotorに足音処理追加~~
- 足音のSoundClipは環境によって変更できるようにする
- ~~地面につける足音切替用のコンポーネントをつくる~~
- ~~そこのColisionEnterでtag==playerのときは足音SEの種類を切り替えるようにする~~

**Comment by RauziDssh** [comment]
ここの実装って地面に足音を切り替えるためのコンポーネントをアタッチする感じですか？
足音のためだけにすべての地面にコンポーネントをつけるのはアレだと思うんで、
プレイヤーの側で判定するのはダメですか？

**Comment by chromee** [comment]
よりよい実装法がありそうでしたらそちらで全然大丈夫です👍

SEの種類を切り替えるとか書いてありますけどSE班の想定としてはAudio Reverb Filterとかいうコンポーネントのパラメータを切り替えたい感じらしいです。

それでそのパラメータなんですけど林くんがなんか各環境でのパラメータ一覧のスクショを取ってslackにあげてくれてたんですけどslack爆破事件でそのスクショ消えてますね…

**Comment by chromee** [comment]
PlayerLocomotorに足音追加とかも書いてありますけど、ここでPlayerLocomotorの挙動がまったく別物になってるので何かしら別のところでやってもらえますと🙇
https://github.com/denx-jp/SSP/pull/129
